/**
 * Regenerates examples/ from the bundled sample inputs.
 *   npm run examples
 *
 * The output files are committed so a reader can see exactly what CleanMath does
 * without installing anything, and so a behaviour change shows up as a diff.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { cleanMathDetailed, DEFAULT_OPTIONS, DELIMITER_MODES } from "../src/lib/cleaner";
import { EXAMPLES } from "../src/lib/defaultText";

/** Resolved from the repo root: this script runs via `npm run examples`. */
const OUT_DIR = join(process.cwd(), "examples");

const fence = (lang: string, body: string) => "```" + lang + "\n" + body + "\n```";

const index: string[] = [
  "# Examples",
  "",
  "Generated by `npm run examples` from the sample inputs in",
  "[`src/lib/defaultText.ts`](../src/lib/defaultText.ts). Each file shows one messy",
  "input and what CleanMath produces in all three delimiter modes.",
  "",
];

for (const [i, example] of EXAMPLES.entries()) {
  const num = String(i + 1).padStart(2, "0");
  const slug = num + "-" + example.id + ".md";

  const parts: string[] = [
    "# " + example.label,
    "",
    "> " + example.blurb,
    "",
    "## Input",
    "",
    fence("markdown", example.text),
    "",
  ];

  for (const mode of DELIMITER_MODES) {
    const { output, issues, blocks } = cleanMathDetailed(example.text, {
      ...DEFAULT_OPTIONS,
      delimiterMode: mode.id,
    });
    parts.push(
      "## Output - " + mode.label + " mode",
      "",
      "`" + mode.hint + "`",
      "",
      fence("latex", output),
      "",
      "_" + blocks + " math block(s) normalized" +
        (issues.length
          ? ", " + issues.length + " issue(s) reported: " +
            issues.map((is) => "line " + is.line).join(", ")
          : ", no issues") +
        "._",
      "",
    );
  }

  writeFileSync(join(OUT_DIR, slug), parts.join("\n"), "utf8");
  index.push("- [" + example.label + "](" + slug + ") - " + example.blurb);
  console.log("wrote examples/" + slug);
}

index.push("");
writeFileSync(join(OUT_DIR, "README.md"), index.join("\n"), "utf8");
console.log("wrote examples/README.md");
